### ISSUE TITLE
Trying out a POST request, "ReadableStream is locked" error

### ISSUE THREAD

**Issue by amundo** [carlosm27/opine_api#1]
Hi, 

Thanks for sharing this interesting and article — hope it’s ok if I ask a rather basic question.

I tried adding a flight to the db with a `POST` request, like this (from the browser, at localhost:3000):

```js
fetch('http://localhost:3000/flight', {
  method: 'POST', 
  body: {
    departure: "Washington DC",
    destination: "Los Angeles",
    flightDuration: 5.5
  }
})
  .catch(e => console.log(e))
```

When I do that, the server crashes with this error:

```
opine_api/$ deno run --allow-net --allow-write --allow-read app.ts
https:\localhost: 3000
```

That’s startup, looks good — I can’t the Paris-Madrid flight at `/flight`. 

But then I try running the fetch above, and this happens:

```
TypeError: ReadableStream is locked.
    at setUpReadableStreamDefaultReader (deno:ext/web/06_streams.js:3022:13)
    at new ReadableStreamDefaultReader (deno:ext/web/06_streams.js:4540:7)
    at acquireReadableStreamDefaultReader (deno:ext/web/06_streams.js:298:12)
    at ReadableStream.getReader (deno:ext/web/06_streams.js:4388:16)
    at WrappedRequest.get #body (https://deno.land/x/opine@2.1.5/src/request.ts:310:46)
    at WrappedRequest.get body (https://deno.land/x/opine@2.1.5/src/request.ts:315:36)
    at file:///Users/pat/Sites/Dev/deno/opine_api/routers/Routers.ts:50:37
    at Layer.handle [as handle_request] (https://deno.land/x/opine@2.1.5/src/router/layer.ts:76:11)
    at next (https://deno.land/x/opine@2.1.5/src/router/route.ts:104:13)
    at Route.dispatch (https://deno.land/x/opine@2.1.5/src/router/route.ts:79:3)
error: Uncaught (in promise) SqliteError: table flights has no column named read
      throw new SqliteError(this._wasm);
            ^
    at DB.prepareQuery (https://deno.land/x/sqlite@v3.1.3/src/db.ts:190:13)
    at https://deno.land/x/denodb@v1.0.40/lib/connectors/sqlite3-connector.ts:59:42
    at Array.map (<anonymous>)
    at SQLite3Connector.query (https://deno.land/x/denodb@v1.0.40/lib/connectors/sqlite3-connector.ts:58:32)
    at Database.query (https://deno.land/x/denodb@v1.0.40/lib/database.ts:240:47)
    at Function._runQuery (https://deno.land/x/denodb@v1.0.40/lib/model.ts:228:42)
    at Function.create (https://deno.land/x/denodb@v1.0.40/lib/model.ts:449:32)
    at file:///Users/pat/Sites/Dev/deno/opine_api/routers/Routers.ts:48:28
    at Layer.handle [as handle_request] (https://deno.land/x/opine@2.1.5/src/router/layer.ts:76:11)
    at next (https://deno.land/x/opine@2.1.5/src/router/route.ts:104:13)
```

**Comment by carlosm27** [comment]
Hi,
Thanks for reporting this issue. I copy/paste the body you are trying to post and I got the same error. It worked when I write the body like this:
{
    "departure": "Washington DC",
    "destination": "Los Angeles",
    "flightDuration": 5.5
  }
The fields between "", and also I have specified the header as "application/json".

Please let me know if this worked for you.

**Comment by amundo** [comment]
Thanks for the quick response. 

Reformatting the body didn’t seem to make a difference, but adding the header changes something. This request:

```js
fetch('http://localhost:3000/flight', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json;charset=utf-8'
    },
    body: {
      departure: "Washington DC",
      destination: "Los Angeles",
      flightDuration: 5.5
    }
  })

```

…doesn’t cause a crash, but it doesn’t seem to add anything to the database either. I should be using `POST` as the `HTTP` verb to do that, no?

**Comment by amundo** [comment]
FWIW I am getting a “Bad Request” in the response:

```js
Response { 
  type: "basic", 
  url: "http://localhost:3000/flight", 
  redirected: false, 
  status: 400, 
  ok: false, 
  statusText: "Bad Request", 
  headers: Headers, 
  body: ReadableStream, 
  bodyUsed: false 
}
```

**Comment by amundo** [comment]
I figured it out! This works. The body has to be JSON encoded:

```js
fetch('http://localhost:3000/flight', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json;charset=utf-8'
    },
    body: JSON.stringify({
      departure: "Washington DC",
      destination: "Los Angeles",
      flightDuration: 5.5
    })
  })
.then(response => console.log(response))
```

Thanks again!

**Comment by carlosm27** [comment]
This is new for me, sorry for not helping. But I'm glad you figure it out and share it here . I'm using a REST Client to make the requests. Also, I found another bug, once you have the server running and modify the database, and stop the server, it will show this 
"Uncaught PermissionDenied: Acceso denegado. (os error 5), open './database.sqlite'
      const rid = Deno.openSync(path, { read: true, write, create }).rid;"

I don't know why, but it "resolve" when the database.sqlite file is deleted.

**Comment by amundo** [comment]
Hmm, must be something to do with how the sqlite db is being opened? 

Are you running deno with `--allow-read`?

**Comment by carlosm27** [comment]
Yes, `deno run --allow-net --allow-write --allow-read app.ts`
